version: 2.1
jobs:
  build:
    macos:
      xcode: "14.3.1"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            xcodebuild -resolvePackageDependencies
      - run:
          name: Build and test
          command: |
            xcodebuild \
              -scheme ResultSportTests \
              -workspace /Users/samyboussair/Desktop/OC_Parcours/P12/ResultSport/ResultSport.xcodeproj \
              -destination generic/platform=iOS \
              test || { echo "Build and test failed"; exit 1; }
