platform :ios do
  lane :tests do |options|
    File.write('ConfigApi.swift', ENV['CONFIG_API_CONTENT'])

   scan(
     clean: options[:clean],
     skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
  end
end
